version: "3.8"
services:
  db:
    container_name: postgres
    image: "postgres:13"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  mock_db:
    container_name: postgresql
    image: "postgres:13"
    ports:
      - "${DB_PORT_TEST}:5432"
    volumes:
      - ./testdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASSWORD_TEST}
      - POSTGRES_DB=${DB_NAME_TEST}